
all:
	@make -C ex00

	@make -C ex01

	@make -C ex02

	@make -C ex03

	@make -C ex04

re:
	@make re -C ex00

	@make re -C ex01

	@make re -C ex02

	@make re -C ex03

	@make re -C ex04

clean:
	@make clean -C ex00

	@make clean -C ex01

	@make clean -C ex02

	@make clean -C ex03

	@make clean -C ex04

fclean:
	@make fclean -C ex00

	@make fclean -C ex01

	@make fclean -C ex02

	@make fclean -C ex03

	@make fclean -C ex04